title: Pack's Hacking Blog
description: "A TIL Blog about Web Hacking by Pack"
author:
  name: "Pack"
  email: "01seunghan@gmail.com"
  url: "https://parkseunghan.github.io/knock-on-til"

baseurl: "/knock-on-til"

source: .
destination: ./_site
permalink: /:title
paginate: 7
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "writeups"
    values:
      layout: "post"

# collections:
#   writeups:
#     output: true
#     permalink: /writeups/:path/


future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Pack"
year : "2024"
